### ISSUE TITLE
Pages not being created

### ISSUE THREAD

**Issue by sobbuh** [marcomelilli/gatsby-airtable-advanced-starter#2]
The index page exists, with links to the blog posts. Clicking on a title takes me to the correct slug link, but there's no page there.

I'm getting the following errors:

"""

warning The GraphQL query in the non-page component "/Users/sobbuh/dev/sobbuh3030/src/templates/post.jsx" will not be run.

warning The GraphQL query in the non-page component "/Users/sobbuh/dev/sobbuh3030/src/templates/tag.jsx" will not be run.

warning The GraphQL query in the non-page component "/Users/sobbuh/dev/sobbuh3030/src/templates/category.jsx" will not be run.

Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

"""

**Comment by krymov** [comment]
Hello!
I had the same issue. It went away when I made sure that all the table names correspond to here: 
https://airtable.com/shrPAHW7PNHlJeTcu/tblwz1XshdQGQlPuf?blocks=hide
https://airtable.com/shrKtgDuvqdcmGKhu/tblKQUYHrJBdh05vl?blocks=hide

In my case I called a table posts and it only worked when I called it Blog and then adjusted names in the env.development.

**Comment by sobbuh** [comment]
Thanks, that solved the problem!
